// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1554097508);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1554097628);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1554109503);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1554097388);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1554097148);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1553667647);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1554097268);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1551093309);
user_pref("browser.laterrun.bookkeeping.sessionCount", 45);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{48d241cf-fd75-434d-8d44-02684a9274dc}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1551304800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 0);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1554097331);
user_pref("browser.onboarding.notification.prompt-count", 7);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1553758589923");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1553760414923");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1554109480225");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1554113080225");
user_pref("browser.search.countryCode", "RO");
user_pref("browser.search.region", "RO");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190214093506");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1554109477");
user_pref("browser.slowStartup.averageTime", 14454);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190214093506");
user_pref("browser.startup.homepage_override.mstone", "60.5.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1551093317344");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "60.5.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Fri, 29 Mar 2019 08:10:44 GMT");
user_pref("extensions.blocklist.pingCountTotal", 17);
user_pref("extensions.blocklist.pingCountVersion", 17);
user_pref("extensions.databaseSchema", 25);
user_pref("extensions.getAddons.cache.lastUpdate", 1554097509);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190214093506");
user_pref("extensions.lastAppVersion", "60.5.1");
user_pref("extensions.lastPlatformVersion", "60.5.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"d636143d-7591-45b2-bc1a-7a2a7f7ad125\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1554097260);
user_pref("media.gmp-manager.buildID", "20190214093506");
user_pref("media.gmp-manager.lastCheck", 1554097221);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1553756158);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "1d532341-44f9-4c25-ba9c-7aa3e7a01357");
user_pref("services.blocklist.addons.checked", 1554097595);
user_pref("services.blocklist.clock_skew_seconds", 33);
user_pref("services.blocklist.gfx.checked", 1554097595);
user_pref("services.blocklist.last_etag", "\"1553900528324\"");
user_pref("services.blocklist.last_update_seconds", 1554097595);
user_pref("services.blocklist.onecrl.checked", 1554097595);
user_pref("services.blocklist.pinning.checked", 1554097595);
user_pref("services.blocklist.plugins.checked", 1554097595);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1553756157);
user_pref("toolkit.startup.last_success", 1554109457);
user_pref("toolkit.telemetry.cachedClientID", "87d56320-6de2-4873-b9e8-9c4d647c9715");
user_pref("toolkit.telemetry.previousBuildID", "20190214093506");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
